 <script type="text/javascript">
    $(document).ready(function(){   //$(document)，将document对象包装成jquery对象，jquery.ready == document里面的window.onload()
	    //调用jquery.validate.js里面的验证方法
	    $("#signupForm").validate({
	        //验证规则
		    rules:{
		    		realname:"required",
		    		username:{
		    		     required:true,
		    		     minlength:5,
		    		     maxlength:8
		    		},
		    		psw:{
		    		     required:true,
		    		     minlength:6,
		    		     maxlength:12
		    		},
		    		psw2:{
		    		     required:true,
		    		     minlength:6,
		    		     maxlength:12,
		    		     equalTo:"#password"
		    		},
		    		gender:"您不能有第三种性别",
		    		age:{
		    			 required:true,
		    			 range:"您的年龄必须介于26~50之间"
		    		}
		    	  },
		    		//显示验证出错的提示信息
		    	message:{
		    		realname:"姓名不能为空",
		    		username:{
		    		     required:"您的登录名不能为空",
		    		     minlength:"您的登录名不能小于5个字符",
		    		     maxlength:"您的登录名不能大于8个字符"
		    		},
		    		psw:{
		    		     required:"您的密码不能为空",
		    		     minlength:"您的密码不能小于6个字符",
		    		     maxlength:"您的密码不能大于12个字符"
		    		},
		    		psw2:{
		    		     required:"您的密码不能为空",
		    		     minlength:"您的密码不能小于6个字符",
		    		     maxlength:"您的密码不能大于12个字符",
		    		     equalTo:"两次输入的密码不一致"
		    		},
		    		gender:"您不能有第三种性别",
		    		age:{
		    			 required:"您的"
		    			 range:"您的年龄必须介于26~50之间"
		    		}
		    	}
	         }
	    });
    });
    </script>