
package csdc.tool.webService.sinoss;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SinossService", targetNamespace = "http://com.eplugger/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SinossService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getApplyProject", targetNamespace = "http://com.eplugger/", className = "csdc.tool.webService.sinoss.GetApplyProject")
    @ResponseWrapper(localName = "getApplyProjectResponse", targetNamespace = "http://com.eplugger/", className = "csdc.tool.webService.sinoss.GetApplyProjectResponse")
    public String getApplyProject(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getApplyAttachment", targetNamespace = "http://com.eplugger/", className = "csdc.tool.webService.sinoss.GetApplyAttachment")
    @ResponseWrapper(localName = "getApplyAttachmentResponse", targetNamespace = "http://com.eplugger/", className = "csdc.tool.webService.sinoss.GetApplyAttachmentResponse")
    public byte[] getApplyAttachment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMidCheckRecords", targetNamespace = "http://com.eplugger/", className = "csdc.tool.webService.sinoss.GetMidCheckRecords")
    @ResponseWrapper(localName = "getMidCheckRecordsResponse", targetNamespace = "http://com.eplugger/", className = "csdc.tool.webService.sinoss.GetMidCheckRecordsResponse")
    public String getMidCheckRecords(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getModifyRecord", targetNamespace = "http://com.eplugger/", className = "csdc.tool.webService.sinoss.GetModifyRecord")
    @ResponseWrapper(localName = "getModifyRecordResponse", targetNamespace = "http://com.eplugger/", className = "csdc.tool.webService.sinoss.GetModifyRecordResponse")
    public String getModifyRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateApplyProject", targetNamespace = "http://com.eplugger/", className = "csdc.tool.webService.sinoss.UpdateApplyProject")
    @ResponseWrapper(localName = "updateApplyProjectResponse", targetNamespace = "http://com.eplugger/", className = "csdc.tool.webService.sinoss.UpdateApplyProjectResponse")
    public String updateApplyProject(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMidCheckProjectMsg", targetNamespace = "http://com.eplugger/", className = "csdc.tool.webService.sinoss.GetMidCheckProjectMsg")
    @ResponseWrapper(localName = "getMidCheckProjectMsgResponse", targetNamespace = "http://com.eplugger/", className = "csdc.tool.webService.sinoss.GetMidCheckProjectMsgResponse")
    public String getMidCheckProjectMsg(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateMsg", targetNamespace = "http://com.eplugger/", className = "csdc.tool.webService.sinoss.UpdateMsg")
    @ResponseWrapper(localName = "updateMsgResponse", targetNamespace = "http://com.eplugger/", className = "csdc.tool.webService.sinoss.UpdateMsgResponse")
    public String updateMsg(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAttachment", targetNamespace = "http://com.eplugger/", className = "csdc.tool.webService.sinoss.GetAttachment")
    @ResponseWrapper(localName = "getAttachmentResponse", targetNamespace = "http://com.eplugger/", className = "csdc.tool.webService.sinoss.GetAttachmentResponse")
    public byte[] getAttachment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
