
package csdc.tool.webService.sinoss;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SinossServiceService", targetNamespace = "http://com.eplugger/", wsdlLocation = "http://218.241.235.188:9521/services/sinossService?wsdl")
public class SinossServiceService
    extends Service
{

    private final static URL SINOSSSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SINOSSSERVICESERVICE_EXCEPTION;
    private final static QName SINOSSSERVICESERVICE_QNAME = new QName("http://com.eplugger/", "SinossServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://218.241.235.188:9521/services/sinossService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SINOSSSERVICESERVICE_WSDL_LOCATION = url;
        SINOSSSERVICESERVICE_EXCEPTION = e;
    }

    public SinossServiceService() {
        super(__getWsdlLocation(), SINOSSSERVICESERVICE_QNAME);
    }

    public SinossServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SINOSSSERVICESERVICE_QNAME);
    }

    public SinossServiceService(URL wsdlLocation) {
        super(wsdlLocation, SINOSSSERVICESERVICE_QNAME);
    }

    public SinossServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SINOSSSERVICESERVICE_QNAME);
    }

    public SinossServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SinossServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns SinossService
     */
    @WebEndpoint(name = "SinossServicePort")
    public SinossService getSinossServicePort() {
        return super.getPort(new QName("http://com.eplugger/", "SinossServicePort"), SinossService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SinossService
     */
    @WebEndpoint(name = "SinossServicePort")
    public SinossService getSinossServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com.eplugger/", "SinossServicePort"), SinossService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SINOSSSERVICESERVICE_EXCEPTION!= null) {
            throw SINOSSSERVICESERVICE_EXCEPTION;
        }
        return SINOSSSERVICESERVICE_WSDL_LOCATION;
    }

}
